### ISSUE TITLE
Logger classes in ch.qos.logback not found when starting up in Docker for Mac

### ISSUE THREAD

**Issue by whummer** [etspaceman/kinesis-mock#154]
Hi, we're sometimes seeing this log output when using kinesis-mock in LocalStack (under Mac OS, Docker version 3.5.2). It doesn't seem to have a noticeable effect from a functional point of view (the service is up and running and available), but would be nice if we can look into fixing this (or suppressing the error message). Please let me know if you need any additional information @etspaceman. Thanks!

```
14:44:41,037 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [ch.qos.logback.classic.AsyncAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.AsyncAppender
at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.AsyncAppender
at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
at 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
at 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
at 	at kinesis.mock.KinesisMockService$.$anonfun$run$2(KinesisMockService.scala:26)
at 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:104)
at 	at cats.effect.internals.IORunLoop$.restartCancelable(IORunLoop.scala:51)
at 	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:100)
at 	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
at 	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
at 	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
at 	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
at 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at 	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
at 	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
at 	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
at 	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:80)
at 	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:58)
at 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:183)
at 	at cats.effect.internals.IORunLoop$.restart(IORunLoop.scala:41)
at 	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:48)
at 	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
at 	at cats.effect.internals.IOAsync$.$anonfun$apply$1(IOAsync.scala:37)
at 	at cats.effect.internals.IOAsync$.$anonfun$apply$1$adapted(IOAsync.scala:37)
at 	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:447)
at 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:156)
at 	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
at 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:484)
at 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
at 	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
at 	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at 	at java.lang.Thread.run(Thread.java:834)
at 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
at 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.AsyncAppender
at 	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:281)
at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
at 	... 54 common frames omitted
14:44:41,037 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@8:71 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.AsyncAppender
at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.AsyncAppender
at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:76)
at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
at 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
at 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
at 	at kinesis.mock.KinesisMockService$.$anonfun$run$2(KinesisMockService.scala:26)
at 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:104)
at 	at cats.effect.internals.IORunLoop$.restartCancelable(IORunLoop.scala:51)
at 	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:100)
at 	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
at 	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
at 	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
at 	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
at 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at 	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
at 	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
at 	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
at 	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:80)
at 	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:58)
at 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:183)
at 	at cats.effect.internals.IORunLoop$.restart(IORunLoop.scala:41)
at 	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:48)
at 	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
at 	at cats.effect.internals.IOAsync$.$anonfun$apply$1(IOAsync.scala:37)
at 	at cats.effect.internals.IOAsync$.$anonfun$apply$1$adapted(IOAsync.scala:37)
at 	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:447)
at 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:156)
at 	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
at 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:484)
at 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
at 	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
at 	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at 	at java.lang.Thread.run(Thread.java:834)
at 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
at 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.AsyncAppender
at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
at 	... 51 common frames omitted
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.AsyncAppender
at 	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:281)
at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
at 	... 54 common frames omitted
14:44:41,037 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR

```

**Comment by etspaceman** [comment]
That is definitely odd - I'll look into that.

**Comment by etspaceman** [comment]
I switched to the AsyncAppender for logback recently for performance reasons, but I never added it to the native-image reflect-config. 

Logs seemed to be working in my CI so I'm a bit confused as to how this is showing up in your area. I'll try to reproduce it on my end.

**Comment by etspaceman** [comment]
0.1.7 being published now, should be ready in about 30 minutes. Once the artifacts are ready, could you re-test on your end and report back?

**Comment by whummer** [comment]
Thanks @etspaceman - will do the testing and take care of the change on LocalStack side. Will re-open the issue in case there are any issues.. Thanks!

**Comment by etspaceman** [comment]
@whummer just following up - do things look OK now?

**Comment by whummer** [comment]
Yes, things are looking good @etspaceman - thanks again! 👍
